### ISSUE TITLE
Incorrect UserAgent.Minor

### ISSUE THREAD

**Issue by t-vorobyova** [ua-parser/uap-go#51]
I have the following user-agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 11_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Coast/5.04.110603 Mobile/15F79 Safari/7534.48.3
BrowserMinorVersion (UserAgent.Minor) is parsed incorrectly, it is parsed as "04" instead of "4"

**Comment by dgoldstein0** [comment]
... that seems pretty reasonable behavior? in 5.04 I wouldn't say the decimal is 4 but rather 04

do other ua-parser implementations handle this differently? if so I could be convinced this is an issue if the golang implementation is in the minority.  Until then I'm assuming this is expected behavior.
